### PR TITLE
Organized links in README

### LINKED ISSUE #118: Hide Demo Link and Repo Link behind short words to improve table view
## Problem
The tech stack, stars are hard to see in the README table

## Solution
We can hide the full links for Demo and Repo behind short words (like Live Link and GitHub) so that the table will get more space, and it also looks clean

### Before
| Clone/Alt of                   | Demo                                                                                                                   | Repo                                                                                                                   | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1Password / LastPass           | https://bitwarden.com/                                                                                                 | https://github.com/bitwarden/mobile                                                                                    | C#, Xamarin                                            | GitHub Repo stars                                                                                                                     |
| 2048                           | https://gh.artemchep.com/2048/#/                                                                                       | https://github.com/AChep/2048                                                                                          | Dart, Flutter                                          | GitHub Repo stars                                                                                                                           |

### After
| Clone/Alt of                   | Demo                                                                                                                   | Repo                                                                                                                   | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ---------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| 1Password / LastPass           |[Live Link](https://bitwarden.com/)                                                                                                | [GitHub](https://github.com/bitwarden/mobile)                                                                                   | C#, Xamarin                                            | GitHub Repo stars                                                                                                                     |
| 2048                           | [Live Link](https://gh.artemchep.com/2048/#/)                                                                                       | [GitHub ](https://github.com/AChep/2048)                                                                                      | Dart, Flutter                                          | GitHub Repo stars                                                                                                                           |

### PR DESCRIPTION
**Pull request by mani-barathi**
closes #118 

[**preview**](https://github.com/mani-barathi/Clone-Wars/tree/refactor-readme#clones-and-alternatives)

### CODE REVIEW

**Comment by GorvGoyl** [comment]
thanks @mani-barathi , could we add the root domain name instead of `Live link`. that way it'll provide better idea about the expected outbound link to the readers.
for example: 
`https://bitwarden.com/`  -> `bitwarden.com`
`https://guaracy.github.io/beads/sites/2048/2048.html` -> `guaracy.github.io`

what do you think?

**Comment by GorvGoyl** [comment]
one more thing, there's a gitlab repo which is mistakenly marked as `Github`

**Comment by mani-barathi** [comment]
@GorvGoyl 
I don't think adding the root domain is really needed, because most of the links are mapped to free hosting services like Heroku, Github, netlify, firebase, vercel and some of the links are mapped to screenshots and youtube links. Also If we are gonna do that again it's gonna take a little more space in the table.

This is just my thought about it but if you really want to do that. we can do that.

**Comment by GorvGoyl** [comment]
I agree it'll be tedious work but I believe it'll improve the end user experience. Providing a generic outbound link `live` doesn't give any context to the reader. It's completely okay if you'd like to skip this task, we can just merge `Repo` column changes.

**Comment by mani-barathi** [comment]
Ok then we can merge the changes for `Repo` column for now. I'll make changes for `Demo` column as you suggested after a few days

**Comment by GorvGoyl** [comment]
perfect. could you please revert the changes from demo column so that i can merge pr.

**Comment by mani-barathi** [comment]
@GorvGoyl I have a good idea
Instead of showing the domain of the website, we can show whether the `demo` link points to a website, or a youtube video or a screenshot, or a gif.
Now we are keeping the table nice and concise and still providing enough info about where the link points to.
| Clone/Alt of                   | Demo                                                                                                                                                                | Repo                                                                                                                                       | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Dropbox                        | [website](https://try.nextcloud.com/)                                                                                                                         | [GitHub](https://github.com/nextcloud/server)                                                                                              | PHP, JS                                                | GitHub Repo stars                                                                                                                     |
| Linear.app                     | [youtube](https://www.youtube.com/watch?v=XVAek-hE5X8)                                                                                                              | [GitHub](https://github.com/tuan3w/linearapp_clone)                                                                                        | React, Redux, TailwindCSS                              | GitHub Repo stars                                                                                                               |
| Netflix                        | [screenshot](https://github.com/karlhadwen/netflix/blob/master/netflix-preview.png)                                                                                 | [GitHub](https://github.com/karlhadwen/netflix)                                                                                            | React, Firebase                                        | GitHub Repo stars                                                                                                                   |
| Spotify                        | [gif](https://drive.google.com/file/d/1KOHOJDGaLeumGqQenzCeeShPqIudCJBX/view)                                                                                       | [GitHub](https://github.com/aashrafh/Oud)                                                                                                  | React                                                  | GitHub Repo stars                                                                                                                         |

whats your thought on this?

**Comment by mani-barathi** [comment]
@GorvGoyl what your thought ?

**Comment by GorvGoyl** [comment]
That's actually good idea if we could indicate whether it's a website video or just screenshots. However, I quickly counted these categories and found out video/screenshots are less than <8%.  
How about we give the domain name and if it's linking to a video/screenshot we can mention that also (although it's already clear by looking at the domain name i.e. youtube.com):

| Clone/Alt of                   | Demo                                                                                                                                                                | Repo                                                                                                                                       | Tech stack                                             | Repo Stars                                                                                                                                                                                     |
| ------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Dropbox                        | [try.nextcloud.com](https://try.nextcloud.com/)                                                                                                                         | [GitHub](https://github.com/nextcloud/server)                                                                                              | PHP, JS                                                | GitHub Repo stars                                                                                                                     |
| Linear.app                     | [youtube.com](https://www.youtube.com/watch?v=XVAek-hE5X8)                                                                                                              | [GitHub](https://github.com/tuan3w/linearapp_clone)                                                                                        | React, Redux, TailwindCSS                              | img.shields.io (screenshot)                                                                                                               |
| Netflix                        | [github.com (screenshot)](https://github.com/karlhadwen/netflix/blob/master/netflix-preview.png)                                                                                 | [GitHub](https://github.com/karlhadwen/netflix)                                                                                            | React, Firebase                                        | GitHub Repo stars                                                                                                                   |
| Spotify                        | [drive.google.com (gif)](https://drive.google.com/file/d/1KOHOJDGaLeumGqQenzCeeShPqIudCJBX/view)                                                                                       | [GitHub](https://github.com/aashrafh/Oud)                                                                                                  | React                                                  | GitHub Repo stars                                                                                                                         |

Also, I increased the total width of table https://gourav.io/clone-wars so it should look fine if we add the domain name i.e. `try.nextcloud.com` instead of `website`.  I wouldn't worry about few extra characters taking some space :). Plus, we significantly reducing the width of `repo` column too.

**Comment by mani-barathi** [comment]
@GorvGoyl ok then I will make changes for demo column as you mentioned and then we can merge this PR ?

**Comment by GorvGoyl** [comment]
sure.

**Comment by mani-barathi** [comment]
@GorvGoyl I've done the changes and also fixed the merge conflicts. Now you can review and merge!
[preview](https://github.com/mani-barathi/Clone-Wars/tree/refactor-readme#clones-and-alternatives)

**Comment by GorvGoyl** [comment]
thank you mani for this amazing contribution 💪💪

**Pull request merged**
