### PR TITLE
add new netflix line

### PR DESCRIPTION
**Pull request by ismailazdad**
This is a personal project netflix clone mobile

### CODE REVIEW

**Comment by ismailazdad** [comment]
Hi @GorvGoyl can you take a look of this PR ?
Thanks 🙏

**Comment by endo-aki22** [comment]
you don't need to put the web app link which is not working.

**Comment by ismailazdad** [comment]
Thanks for your response. The web app links work but only in mobile mode

**Comment by endo-aki22** [comment]
> Thanks for your response. The web app links work but only in mobile mode

we are not sure if yours can be a good alternative. because every page looks different from Netflix. also web link doesn't look good.
However, it can be a new alternative which uses `[capacitor](https://capacitorjs.com/)` with React to build a mobile app.

**Pull request merged**
