### PR TITLE
Added "Clones with Tutorials" Table

### PR DESCRIPTION
**Pull request by dimi-fn**
1. Fixed table's formatting: 

- Added "**Demo Link**" and "**Repo Link**" _hyperlinks_ instead of displaying complete URLs for all clones (from "`1Password / LastPass`" to "`Zapier`"). In this way, you do not need to scroll right on the table to view all columns. Before that, if someone e.g. wanted to find clones based on a specific tech stack or GitHub stars, they should first scroll right and left continuously to crosscheck them. 

- Added "hr" for the _variants of the very same clone_ (e.g., clone "2048" and clone "Google Analytics" are now displayed in 1 row with 4 thematic breaks respectively instead of 4 rows for every clone). Exceptions: Trello, Twitter, and WhatsApp where I had an issue when so many "hr" were used, so I left those clones to repeat themselves.

<hr>

2. Deleted the text "`_(scroll right on table to see all 5 columns)_`" since it is no longer necessary to be noted.

<hr>

3. Added a new **section** and introduced a new **table** called "**Clones with Tutorial**" with course material provided based on @QuincyLarson suggestion, and since @GorvGoyl you seemed to agree with this idea.

- Same columns here as before, but I also introduced 2 new ones being: "**Article**" & "**Tutorial**".
- I also added 5 images to the "img" directory for displaying a demo for the respective tutorials.

<hr>

This is how changes would look like for "1. Fixed table's formatting":

<br>...and for "3. Added a new **section** and introduced a new **table** called "**Clones with Tutorial**" with course material": <br>

### CODE REVIEW

**Review by Arun-kc — CHANGES_REQUESTED** [review]
Looks good to me @dimi-fn 👍 But you forgot to club together Trello, Twitter, Typeform, and Whatsapp just like the others. Make those changes and it will be good to go. Good work!!

**Review by Arun-kc — APPROVED** [review]
Perfect @dimi-fn 👍  @GorvGoyl I think it's ready to merge. Please check it out.

**Comment by dimi-fn** [comment]
Hi @Arun-kc, thank you for your feedback. With the last commit, I merged those apps that you indicated, however for Trello and Twitter it gets quite confusing (demos and repos are not aligned). I tried to fix the spaces between  "hr" across all table in case it had to do with that, however, this did not solve the problem, it maybe has to do with Github's markdown. Let me know how it looks to you.

**Comment by GorvGoyl** [comment]
thank you for PR guys.

**Comment by GorvGoyl** [comment]
Thank you for PR guys. 

Github doesn't support merging rows in markdown [see stackoverflow question.](https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown)
Though adding `<hr>` is a workaround but I think it'll make hard for other contributors to add their clones when adding to the same site (trello, netflix etc) as it looks cluttered. Will be hard for me to review also.

**Comment by GorvGoyl** [comment]
> I also added 5 images to the "img" directory for displaying a demo for the respective tutorials.

IMO, we should give link to the screenshot/demo section from their github repo/article if present instead of storing in our repo. If link is not present we can also provide link to the [correct timestamp](https://www.lifewire.com/youtube-link-to-specific-time-3486675) of youtube video where the demo was shown.

**Comment by GorvGoyl** [comment]
> Same columns here as before, but I also introduced 2 new ones being: "Article" & "Tutorial".

Can we use just one column for providing external link whether it is Tutorial/Article/course (_i.e. single source of truth_). I'm assuming that mentioned link would provide any further supported links like youtube/codesandbox/blog-series etc.
In freecodecamp case we can just provide a single link to the freecodecamp article where students can go and explore any supported links like youtube video.

**Comment by dimi-fn** [comment]
> Thank you for PR guys.
> 
> Github doesn't support merging rows in markdown [see stackoverflow question.](https://stackoverflow.com/questions/46621765/can-i-merge-table-rows-in-markdown)
> Though adding `<hr>` is a workaround but I think it'll make hard for other contributors to add their clones when adding to the same site (trello, netflix etc) as it looks cluttered. Will be hard for me to review also.

Commit 4751328 undid everything. This is why I also changed PR's title name. What this PR eventually did was the creation of the 2nd table "clones with tutorials". You can visit my [forked repo](https://github.com/dimi-fn/Clone-Wars) if you find it hard to edit the changes here because of the previous commits. As you will see, everything remains the same as before this PR was created, except for the 2nd table.

**Comment by dimi-fn** [comment]
> > I also added 5 images to the "img" directory for displaying a demo for the respective tutorials.
> 
> IMO, we should give link to the screenshot/demo section from their github repo/article if present instead of storing in our repo. If link is not present we can also provide link to the [correct timestamp](https://www.lifewire.com/youtube-link-to-specific-time-3486675) of youtube video where the demo was shown.

Commit 4751328 fixed that. In your images directory, you will have what you previously had. I have provided screenshots in the demo hyperlinks of the table.

**Comment by dimi-fn** [comment]
> > Same columns here as before, but I also introduced 2 new ones being: "Article" & "Tutorial".
> 
> Can we use just one column for providing external link whether it is Tutorial/Article/course (_i.e. single source of truth_). I'm assuming that mentioned link would provide any further supported links like youtube/codesandbox/blog-series etc.
> In freecodecamp case we can just provide a single link to the freecodecamp article where students can go and explore any supported links like youtube video.

Done. 

The table is in HTML format, hence if someone wants to add material upon an existed clone then _rowspan_ can be used (as indicated in the StackOverflow post you indicated), otherwise the addition of other rows in the table. IMO, review also would be manageable.

**Comment by GorvGoyl** [comment]
Thank you @dimi-fn for your efforts, much appreciated. will merge it.

**Pull request merged**
