### PR TITLE
Added Ubuntu Clone Link

### PR DESCRIPTION
**Pull request by vivek9patel**
Live Demo - https://vivek9patel.github.io
GitHub repo - https://github.com/vivek9patel/vivek9patel.github.io

### CODE REVIEW

**Review by Wangtt185 — APPROVED** [review]

**Comment by GorvGoyl** [comment]
Great repo. Though, there are some merge conflicts, could you resolve and submit again.

**Comment by vivek9patel** [comment]
sure!

**Comment by vivek9patel** [comment]
resolved! @GorvGoyl

**Comment by vivek9patel** [comment]
wait something is wrong

**Comment by vivek9patel** [comment]
it's not done yet
your readme is messed up

**Comment by vivek9patel** [comment]
do one thing, revert the last commit I'll make PR from new branch!

**Comment by GorvGoyl** [comment]
no problem. i resolved it.

**Review by Wangtt185 — COMMENTED** [review]
1

**Pull request merged**
