### PR TITLE
Add New IMDB clone & remove broken IMDB clone

### PR DESCRIPTION
**Pull request by zerone0x**

### CODE REVIEW

**Comment by zerone0x** [comment]
Hi @tosh  @oddrationale @dirkkelly  @ivarconr  Could you help review this PR, I added a new IMDB clone and remove broken IMDB clone. Thanks!

**Comment by oddrationale** [comment]
Hey, @zerone0x! I am not a maintainer nor do I have write access to this repository. Sorry!

**Comment by zerone0x** [comment]
@GorvGoyl Could you please help review this? Thanks

**Comment by zerone0x** [comment]
@Pritamgit2002

**Review by EliasLeguizamon123 — APPROVED** [review]
Very nice contribution @zerone0x thanks!

**Pull request merged**
